/**
 * Auto-generated migration map for admin-console
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration admin-console
 */

import * as Generated from '@autional/shared/generated/api';
import { apiClient } from '@autional/shared';

export const getUsers = Generated.adminUsers;
export const getUser = Generated.adminUsersByUsers;
export const createUser = Generated.adminUsersPost;
export const updateUser = Generated.adminUsersByUsersPut;
export const deleteUser = Generated.adminUsersByUsersDelete;
export const updateUserStatus = Generated.adminUsersStatusByUsersPut;
export const unlockUser = Generated.adminUsersAccountUnlocksByUsersPost;
export const resetUserPassword = Generated.adminUsersPasswordResetsByUsersPost;
export const resetUserMFA = Generated.adminMfaResetByResetDelete;
export const changePassword = Generated.authMePasswordPut;
export const getUserRoles = Generated.adminUsersRolesByUsers;
export const assignUserRoles = Generated.adminUsersRolesByUsersPost;
export const removeUserRoles = Generated.adminUsersRolesByUsersDelete;
export const getUserPermissions = Generated.adminUsersPermissionsByUsers;
export const getUserLoginHistories = Generated.adminUsersLoginHistoriesByUsers;
export const getRoles = Generated.adminRoles;
export const getRole = Generated.adminRolesByRoles;
export const createRole = Generated.adminRolesPost;
export const updateRole = Generated.adminRolesByRolesPut;
export const deleteRole = Generated.adminRolesByRolesDelete;
export const getRolePermissions = Generated.adminRolesPermissionsByRoles;
export const assignRolePermissions = Generated.adminRolesPermissionsByRolesPost;
export const removeRolePermissions = Generated.adminRolesPermissionsByRolesDelete;
export const getPermissions = Generated.adminPermissions;
export const createPermission = Generated.adminPermissionsPost;
export const updatePermission = Generated.adminPermissionsByPermissionsPut;
export const deletePermission = Generated.adminPermissionsByPermissionsDelete;
export const getDepartments = Generated.adminTenantsDepartmentsByTenants;
export const createDepartment = Generated.adminTenantsDepartmentsByTenantsPost;
export const updateDepartment = Generated.adminTenantsDepartmentsByTenantsByDepartmentsPut;
export const deleteDepartment = Generated.adminTenantsDepartmentsByTenantsByDepartmentsDelete;
export const getMembers = Generated.adminTenantsMembersByTenants;
export const inviteMember = Generated.adminTenantsMembersInviteByTenantsPost;
export const getSessions = Generated.adminSessions;
export const deleteSession = Generated.sessionsBySessionsDelete;
export const getActiveSessionCount = Generated.adminSessionsActiveCount;
export const getAuditLogs = Generated.adminAuditLogs;
export const getAuditStats = Generated.adminAuditStats;
export const verifyAuditChain = Generated.adminAuditVerificationsPost;
export const getTenantBranding = Generated.adminTenantsBrandingByTenants;
export const updateTenantBranding = Generated.adminTenantsBrandingByTenantsPut;
export const getDataClassification = (tenantId: string) =>
	Generated.adminTenantsDataClassificationByTenants(tenantId);
export const updateDataClassification = (tenantId: string, data: any) =>
	Generated.adminTenantsDataClassificationByTenantsPost(tenantId, data);
export const getApplications = Generated.adminTenantsApplicationsByTenants;
export const createApplication = Generated.adminTenantsApplicationsByTenantsPost;
export const updateApplication = Generated.adminTenantsApplicationsByTenantsByApplicationsPut;
export const deleteApplication = Generated.adminTenantsApplicationsByTenantsByApplicationsDelete;
export const updateMember = Generated.adminTenantsMembersByTenantsByMembersPut;
export const removeMember = Generated.adminTenantsMembersByTenantsByMembersDelete;
export const getPasswordPolicy = Generated.adminSecurityPasswordPolicy;
export const updatePasswordPolicy = Generated.adminSecurityPasswordPolicyPut;
export const getMFARiskPolicy = Generated.adminMfaRiskPolicy;
export const updateMFARiskPolicy = Generated.adminMfaRiskPolicyPut;
export const getSecurityPolicy = Generated.adminTenantsSecurityPolicyByTenants;
export const updateSecurityPolicy = Generated.adminTenantsSecurityPolicyByTenantsPut;
export const getIdentityProviders = Generated.adminIdentityProviders;
export const createIdentityProvider = Generated.adminIdentityProvidersPost;
export const updateIdentityProvider = Generated.adminIdentityProvidersByIdentityProvidersPut;
export const deleteIdentityProvider = Generated.adminIdentityProvidersByIdentityProvidersDelete;
export const testIdentityProvider = Generated.adminIdentityProvidersTestByIdentityProvidersPost;
export const getWebhooks = Generated.adminTenantsWebhooksByTenants;
export const createWebhook = Generated.adminTenantsWebhooksByTenantsPost;
export const updateWebhook = Generated.adminTenantsWebhooksByTenantsByWebhooksPut;
export const deleteWebhook = Generated.adminTenantsWebhooksByTenantsByWebhooksDelete;
export const testWebhook = Generated.adminTenantsWebhooksTestByTenantsByWebhooksPost;
export const getApiKeys = (tenantId: string) => Generated.adminTenantsApiKeysByTenants(tenantId);
export const createApiKey = (tenantId: string, data: any) =>
	Generated.adminTenantsApiKeysByTenantsPost(tenantId, data);
export const rotateApiKey = (tenantId: string, keyId: string) =>
	Generated.adminTenantsApiKeysRotateByTenantsByApiKeysPost(tenantId, keyId);
export const revokeApiKey = (tenantId: string, keyId: string) =>
	Generated.adminTenantsApiKeysByTenantsByApiKeysDelete(tenantId, keyId);
export const getAuditLogDetail = Generated.adminAuditLogsByLogs;
export const exportAuditLogs = Generated.adminAuditExportPost;

// Audit: Export
export const getExportJobs = Generated.adminAuditExportJobs;
export const downloadExportJob = Generated.adminAuditExportDownloadByExport;

// Audit: Hash Chain & Merkle
export const getHashChain = Generated.adminAuditHashchainByHashchain;
export const getMerkleProof = Generated.adminAuditMerkleProof;
export const getVerifications = Generated.adminAuditVerifications;

// Audit: Archive
export const getArchiveStatus = Generated.adminAuditArchiveStatus;
export const triggerArchive = Generated.adminAuditArchivePost;

// Audit: Alerts
export const getAlerts = Generated.adminAuditAlerts;
export const getAlertById = Generated.adminAuditAlertsByAlerts;
export const updateAlertStatus = Generated.adminAuditAlertsStatusByAlertsPut;
export const assignAlert = Generated.adminAuditAlertsAssignByAlertsPost;

// Audit: Anomalies
export const getAnomalies = Generated.adminAuditAnomalies;
export const getAnomalyById = Generated.adminAuditAnomaliesByAnomalies;
export const updateAnomalyStatus = Generated.adminAuditAnomaliesStatusByAnomaliesPut;
export const assignAnomaly = Generated.adminAuditAnomaliesAssignByAnomaliesPost;
export const addAnomalyComment = Generated.adminAuditAnomaliesCommentByAnomaliesPost;
export const getAnomalyTimeline = Generated.adminAuditAnomaliesTimelineByAnomalies;
export const getRelatedAnomalies = Generated.adminAuditAnomaliesRelatedByAnomalies;
export const detectAnomalies = Generated.adminAuditAnomaliesDetectPost;
export const linkAnomalyToCase = Generated.adminAuditAnomaliesLinkByAnomaliesPost;

// Audit: SIEM Connectors
export const getSIEMConnectors = Generated.adminAuditSiemConnectors;
export const createSIEMConnector = Generated.adminAuditSiemConnectorsPost;
export const updateSIEMConnector = Generated.adminAuditSiemConnectorsByConnectorsPut;
export const deleteSIEMConnector = Generated.adminAuditSiemConnectorsByConnectorsDelete;
export const testSIEMConnector = Generated.adminAuditSiemConnectorsTestByConnectorsPost;

// Audit: Retention
export const getRetentionPolicy = Generated.adminAuditRetentionPolicy;
export const saveRetentionPolicy = Generated.adminAuditRetentionPolicyPut;

// Audit: Financial Events
export const getWalletEvents = Generated.adminAuditWalletEvents;
export const getBillingEvents = Generated.adminAuditBillingEvents;
export const getPaymentEvents = Generated.adminAuditPaymentEvents;

// Audit: Hash Chain & Merkle (continued)
export const getHashChainVerifyByDate = Generated.adminAuditHashchainVerifyByDateByHashchain;
export const getMerkleRoot = Generated.adminAuditMerkleRoot;
export const getMerkleProofs = Generated.adminAuditMerkleProofsPost;

// Audit: Export (continued)
export const getExportJobStatus = Generated.adminAuditExportStatusByExport;

// Audit: Reports
export const getSecurityReport = Generated.adminAuditReportsSecurity;
export const getComplianceReport = Generated.adminAuditReportsCompliance;

// Audit: SSE Stream
export const getAuditStream = Generated.adminAuditStream;

// Audit: Compliance
export const getPIAs = Generated.adminAuditCompliancePias;
export const createPIA = Generated.adminAuditCompliancePiasPost;
export const getBreaches = Generated.adminAuditComplianceBreaches;
export const createBreach = Generated.adminAuditComplianceBreachesPost;
export const getDataClassifications = Generated.adminAuditComplianceDataClassifications;
export const createDataClassification = Generated.adminAuditComplianceDataClassificationsPost;
export const getCrossBorderTransfers = Generated.adminAuditComplianceCrossBorder;
export const createCrossBorderTransfer = Generated.adminAuditComplianceCrossBorderPost;
export const getAIDecisions = Generated.adminAuditComplianceAiDecisions;
export const createAIDecision = Generated.adminAuditComplianceAiDecisionsPost;
export const getCleanupRecords = Generated.adminAuditComplianceCleanupRecords;
export const getCleanupRecord = Generated.adminAuditComplianceCleanupRecordsByCleanupRecords;
export const createCleanupRecord = Generated.adminAuditComplianceCleanupRecordsPost;
export const getSODRules = Generated.adminAuditComplianceSodRules;
export const getRoleActions = Generated.adminAuditComplianceRoleActions;

// Audit: Tenant Config
export const getTenantConfig = Generated.adminAuditTenantConfig;
export const saveTenantConfig = Generated.adminAuditTenantConfigPut;

// Billing: Subscription
export const getBillingSubscription = Generated.billingSubscriptionBySubscription;
export const changeBillingPlan = Generated.adminBillingSubscriptionChangePlanBySubscriptionPost;
export const getBillingUsage = Generated.billingUsageCurrentByUsage;
export const getBillingStatistics = Generated.billingStatisticsByStatistics;
export const getBillingRecords = Generated.billingRecordsByRecords;
export const getInvoice = Generated.billingInvoiceByInvoice;
export const exportInvoice = Generated.billingInvoiceExportByInvoice;

// Billing: Plans CRUD
export const getBillingPlans = Generated.adminBillingPlans;
export const createBillingPlan = Generated.adminBillingPlansPost;
export const updateBillingPlan = Generated.adminBillingPlansByPlansPut;
export const deleteBillingPlan = Generated.adminBillingPlansByPlansDelete;

// Billing: Payment Gateways
export const createPaymentGateway = Generated.adminBillingPaymentGatewaysPost;
export const updatePaymentGateway = Generated.adminBillingPaymentGatewaysByPaymentGatewaysPut;

// Billing: Credit Notes
export const createCreditNote = Generated.adminBillingInvoiceCreditNoteByInvoicePost;

// Billing: Refund Approvals
export const createRefundApproval = Generated.adminBillingRefundApprovalPost;
export const getRefundApproval = Generated.adminBillingRefundApprovalByRefundApproval;
export const approveRefund = Generated.adminBillingRefundApprovalApproveByRefundApprovalPost;
export const rejectRefund = Generated.adminBillingRefundApprovalRejectByRefundApprovalPost;
export const executeRefund = Generated.adminBillingRefundApprovalExecuteByRefundApprovalPost;

// Billing: Tax & Revenue
export const getTaxExport = Generated.adminBillingTaxExport;
export const getRevenueAmortization = Generated.adminBillingRevenueAmortization;

// Billing: Dunning
export const getDunningSettings = Generated.adminBillingDunningSettingsByDunningSettings;
export const updateDunningSettings = Generated.adminBillingDunningSettingsByDunningSettingsPut;

// Billing: Subscription Management
export const updateSubscription = Generated.adminBillingSubscriptionBySubscriptionPut;
export const deleteSubscription = Generated.adminBillingSubscriptionBySubscriptionDelete;
export const extendTrial = Generated.adminBillingSubscriptionExtendTrialBySubscriptionPost;
export const cancelTrial = Generated.adminBillingSubscriptionCancelTrialBySubscriptionPost;
export const rollbackPlan = Generated.adminBillingSubscriptionRollbackPlanBySubscriptionPost;

// Billing: App Pricing
export const getAppPricing = Generated.adminBillingSubscriptionAppsPricingBySubscriptionByApps;
export const configureAppPricing =
	Generated.adminBillingSubscriptionAppsPricingBySubscriptionByAppsPost;

// Billing: Balance/Credit
export const getBillingBalance = Generated.billingBalance;
export const getCreditBalance = Generated.billingCreditBalanceByCreditBalance;

// Billing: Public Plans
export const getPublicBillingPlans = Generated.billingPlans;

export const getDSARs = Generated.adminComplianceGdprDsar;
export const updateDSAR = Generated.adminComplianceGdprDsarByDsarPut;
export const executeErasure = Generated.adminComplianceGdprRightToErasurePost;
export const getRetentionPolicies = Generated.adminComplianceRetentionPolicies;
export const getComplianceSODRules = Generated.adminComplianceSodRules;
export const getISOControls = Generated.adminComplianceIso27001Controls;
export const getFiles = Generated.files;
export const uploadFile = Generated.filesUploadUrlPost;
export const getStorageQuota = Generated.storageQuota;
export const getStorageStats = Generated.adminStorageStats;
export const getStorageTrash = Generated.storageTrash;
export const restoreTrashItem = Generated.storageTrashRestoreByTrashPost;
export const deleteTrashItem = Generated.storageTrashByTrashDelete;

// Wallet
export const getWalletSummary = Generated.adminWalletsTenantsSummaryByTenants;
export const getWalletTransactions = Generated.adminWalletsTenantsTransactionsByTenants;
export const getWalletDisputes = Generated.adminWalletsTenantsDisputesByTenants;
export const resolveDispute = Generated.adminWalletsTenantsDisputesResolveByTenantsByDisputesPost;
export const adjustWallet = Generated.adminWalletsUsersAdjustByUsersPost;

// Wallet: Coupons
export const updateCoupon = Generated.adminWalletsCouponsByCouponsPut;
export const deleteCoupon = Generated.adminWalletsCouponsByCouponsDelete;

// Wallet: Fraud Rules
export const getFraudRules = Generated.adminWalletsFraudRules;
export const updateFraudRules = Generated.adminWalletsFraudRulesPost;

// Wallet: Reconciliation
export const getReconciliation = Generated.adminWalletsReconciliation;

// Wallet: Batch Operations
export const batchFreezeWallets = Generated.adminWalletsBatchFreezePost;
export const batchUnfreezeWallets = Generated.adminWalletsBatchUnfreezePost;

// Wallet: Policy
export const getWalletPolicy = Generated.adminWalletsTenantsAppsPolicyByTenantsByApps;
export const updateWalletPolicy = Generated.adminWalletsTenantsAppsPolicyByTenantsByAppsPut;

// Wallet: App Summary
export const getWalletAppSummary = Generated.adminWalletsTenantsAppsSummaryByTenantsByApps;

// Wallet: CRUD
export const updateWallet = Generated.adminWalletsByWalletsPut;
export const deleteWallet = Generated.adminWalletsByWalletsDelete;

// Points: Rules
export const getPointRules = Generated.adminPointRules;
export const createPointRule = Generated.adminPointRulesPost;
export const updatePointRule = Generated.adminPointRulesByPointRulesPut;
export const deletePointRule = Generated.adminPointRulesByPointRulesDelete;
export const testPointRule = Generated.adminPointRulesTestPost;

// Points: Accounts
export const getPointAccounts = Generated.adminPoints;
export const batchEarnPoints = Generated.adminPointsBatchEarnPost;
export const applyPointRule = Generated.adminPointsApplyRulePost;
export const adjustPoints = Generated.adminPointsAdjustByPointsPost;
export const expirePoints = Generated.adminPointsExpireByPointsPost;
export const freezePoints = Generated.adminPointsFreezeByPointsPost;
export const unfreezePoints = Generated.adminPointsUnfreezeByPointsPost;
export const updatePointAccountStatus = Generated.adminPointsStatusByPointsPut;

export const getNotificationTemplates = Generated.notificationsTemplates;
export const createNotificationTemplate = Generated.adminNotificationsTemplatesPost;
export const updateNotificationTemplate = Generated.adminNotificationsTemplatesByTemplatesPut;
export const deleteNotificationTemplate = Generated.adminNotificationsTemplatesByTemplatesDelete;
export const testNotification = Generated.notificationsTestPost;
export const getNotificationStats = Generated.notificationsStats;
export const getEventMappings = Generated.notificationsEventMappings;
export const getEventMapping = Generated.notificationsEventMappingsByEventMappings;
export const createEventMapping = Generated.adminNotificationsEventMappingsPost;
export const updateEventMapping = Generated.adminNotificationsEventMappingsByEventMappingsPut;
export const deleteEventMapping = Generated.adminNotificationsEventMappingsByEventMappingsDelete;
export const getGlobalVariables = Generated.notificationsGlobalVariables;
export const getGlobalVariable = Generated.notificationsGlobalVariablesByGlobalVariables;
export const createGlobalVariable = Generated.adminNotificationsGlobalVariablesPost;
export const updateGlobalVariable = Generated.adminNotificationsGlobalVariablesByGlobalVariablesPut;
export const deleteGlobalVariable =
	Generated.adminNotificationsGlobalVariablesByGlobalVariablesDelete;
export const getCommunicationTemplates = Generated.communicationTemplates;
export const getCommunicationTemplateStats = Generated.communicationTemplateStats;
export const getCommunicationTemplatesAvailable = Generated.communicationTemplatesAvailable;
export const getCommunicationDashboard = Generated.communicationDashboard;
export const getCommunicationLogs = Generated.communicationLogs;
export const getPlatformCommunicationStats = Generated.adminCommunicationPlatformStats;
export const getPlatformNotificationStats = Generated.adminNotificationsPlatformStats;
export const getTenantStats = Generated.adminTenantsStats;
export const getCommunicationHealth = Generated.communicationHealthByHealth;

export const getCommunicationProviders = Generated.communicationProviders;
export const createCommunicationProvider = Generated.adminCommunicationProvidersPost;
export const updateCommunicationProvider = Generated.adminCommunicationProvidersByProvidersPut;
export const deleteCommunicationProvider = Generated.adminCommunicationProvidersByProvidersDelete;

export const createCommunicationTemplate = Generated.adminCommunicationTemplatesPost;
export const updateCommunicationTemplate = Generated.adminCommunicationTemplatesByTemplatesPut;
export const deleteCommunicationTemplate = Generated.adminCommunicationTemplatesByTemplatesDelete;
export const cloneCommunicationTemplateToLocale =
	Generated.adminCommunicationTemplatesCloneToLocaleByTemplatesPost;

export const publishAnnouncement = Generated.adminAnnouncementsPublishByAnnouncementsPost;
export const unpublishAnnouncement = Generated.adminAnnouncementsUnpublishByAnnouncementsPost;

export const broadcastNotification = Generated.adminNotificationsBroadcastPost;
export const getNotificationsReadReport = Generated.notificationsReadReport;
export const getAllTenants = Generated.adminTenants;
export const getTenantDetail = Generated.adminTenantsByTenants;
export const createTenant = Generated.adminTenantsPost;
export const updateTenant = Generated.adminTenantsByTenantsPut;
export const deleteTenant = Generated.adminTenantsByTenantsDelete;
export const activateTenant = Generated.adminTenantsActivateByTenantsPost;
export const suspendTenant = Generated.adminTenantsSuspendByTenantsPost;
export const getTenantQuota = Generated.adminTenantsQuotaByTenants;
export const updateTenantQuota = Generated.adminTenantsQuotaByTenantsPut;
export const getAnnouncements = Generated.adminAnnouncements;
export const createAnnouncement = Generated.adminAnnouncementsPost;
export const updateAnnouncement = Generated.adminAnnouncementsByAnnouncementsPut;
export const deleteAnnouncement = Generated.adminAnnouncementsByAnnouncementsDelete;

// Auth Config
export const getAuthConfig = Generated.adminSecurityAuthConfig;
export const updateAuthConfig = Generated.adminSecurityAuthConfigPut;

// Approval
export const getPendingMembers = Generated.adminTenantsMembersPendingByTenants;
export const approveMember = Generated.adminTenantsMembersApproveByTenantsByMembersPost;
export const rejectMember = Generated.adminTenantsMembersRejectByTenantsByMembersPost;
export const batchApproveMembers = Generated.adminTenantsMembersBatchApproveByTenantsPost;

// Password Status
export const getPasswordStatus = Generated.adminUsersPasswordStatusByUsers;

// Status-service endpoints for ops page
export { statusOverview } from '@autional/shared/generated/api';

// Ops — Grafana URLs and topology
// 基址 = 构建期注入的 VITE_GRAFANA_URL；dev 回落本机端口，生产构建未注入时由
// vite.config.ts 直接 fail-build —— 此处不做 localhost 静默回落（PL-56）。
const GRAFANA_BASE: string = String(
	(import.meta as any).env.VITE_GRAFANA_URL ||
		((import.meta as any).env.DEV ? 'http://localhost:20300' : ''),
).replace(/\/+$/, '');
export const isGrafanaConfigured = GRAFANA_BASE !== '';
export const ops = {
	topology: Generated.adminTopology,
	rateLimits: Generated.adminRateLimits,
	grafanaOverviewUrl: `${GRAFANA_BASE}/d/authms-overview?kiosk=full`,
	grafanaServicesUrl: (service: string) =>
		`${GRAFANA_BASE}/d/authms-services?var-service=${service}&kiosk=full`,
};

// Profile Service
export const searchProfiles = Generated.adminProfiles;
export const archiveProfile = Generated.adminProfilesArchiveByProfilesPost;
export const exportProfile = Generated.adminProfilesExportByProfiles;
export const getProfile = Generated.profilesByProfiles;
export const getProfileCompleteness = Generated.profilesCompletenessByProfiles;
export const getProfilePrivacy = Generated.profilesPrivacyByProfiles;
export const getProfilePrivacyImpact = Generated.profilesPrivacyImpactByProfiles;
export const getProfilePublic = Generated.profilesPublicByProfiles;
export const getProfileAvatar = Generated.profileAvatar;

// Invitation Config
export const getInvitationConfig = Generated.adminTenantsInvitationConfigByTenants;
export const updateInvitationConfig = (tenantId: string, data: any) =>
	Generated.adminTenantsInvitationConfigByTenantsPut(tenantId, data);

// Quota
export const updateQuota = (tenantId: string, data: any) =>
	Generated.adminTenantsQuotaByTenantsPut(tenantId, data);

// App Roles
export const getAppDefaultRoles = (tenantId: string, appId: string) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplications(tenantId, appId);
export const createAppDefaultRole = (tenantId: string, appId: string, data: any) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplicationsPost(tenantId, appId, data);
export const updateAppDefaultRole = (tenantId: string, appId: string, roleId: string, data: any) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplicationsByRolesPut(
		tenantId,
		appId,
		roleId,
		data,
	);
export const deleteAppDefaultRole = (tenantId: string, appId: string, roleId: string) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplicationsByRolesDelete(
		tenantId,
		appId,
		roleId,
	);
export const getAppMembers = (tenantId: string, appId: string, params?: any) =>
	Generated.adminTenantsApplicationsMembersByTenantsByApplications(tenantId, appId, params);
export const assignAppMember = (tenantId: string, appId: string, data: any) =>
	Generated.adminTenantsApplicationsMembersByTenantsByApplicationsPost(tenantId, appId, data);
export const revokeAppMember = (tenantId: string, appId: string, roleId: string) =>
	Generated.adminTenantsApplicationsMembersByTenantsByApplicationsByMembersDelete(
		tenantId,
		appId,
		roleId,
	);

// Status Service
export const getIncidents = Generated.statusIncidents;
export const getIncident = Generated.statusIncidentsByIncidents;
export const createIncident = Generated.statusIncidentsPost;
export const updateIncident = Generated.statusIncidentsByIncidentsPut;
export const deleteIncident = Generated.statusIncidentsByIncidentsDelete;
export const addIncidentUpdate = Generated.statusIncidentsUpdatesByIncidentsPost;
export const getMaintenances = Generated.statusMaintenances;
export const getMaintenance = Generated.statusMaintenancesByMaintenances;
export const createMaintenance = Generated.statusMaintenancesPost;
export const updateMaintenance = Generated.statusMaintenancesByMaintenancesPut;
export const deleteMaintenance = Generated.statusMaintenancesByMaintenancesDelete;
export const getOverview = Generated.statusOverview;

export const getSubscribers = Generated.statusSubscriptions;

// Secret Service — 密钥管理
export const getSecrets = Generated.adminSecrets;
export const getSecretDetail = Generated.adminSecretsDetail;
export const createSecret = Generated.adminSecretsPost;
export const updateSecret = Generated.adminSecretsUpdatePost;
export const deleteSecret = Generated.adminSecretsItemKeyByKeyDelete;
export const rotateSecret = Generated.adminSecretsRotatePost;
export const revokeSecret = Generated.adminSecretsRevokePost;
export const getSecretVersions = Generated.adminSecretsVersions;
export const getSecretVersionValue = Generated.adminSecretsVersionsValuePost;
export const batchRevokeSecrets = Generated.adminSecretsBatchRevokePost;
export const batchDeleteSecrets = Generated.adminSecretsBatchDeletePost;
export const getEncryptionKeys = Generated.adminSecretsEncryptionKeys;

// Server Logs — 服务错误日志
export const getServerLogs = Generated.adminAuditServerLogs;
export const getServerLogServices = Generated.adminAuditServerLogsServices;

// ABAC Policies (inline API since generated API doesn't have ABAC yet)
export const getAbacPolicies = Generated.adminAbacPolicies;
export const createAbacPolicy = Generated.adminAbacPoliciesPost;
export const getAbacPolicy = Generated.adminAbacPoliciesByAbacPolicies;
export const updateAbacPolicy = Generated.adminAbacPoliciesByAbacPoliciesPut;
export const deleteAbacPolicy = Generated.adminAbacPoliciesByAbacPoliciesDelete;

// FeatureGates — Phase 0b: 租户按订阅计划启用的功能开关
// TODO: Phase 1 替换为 billing-service 的真实 API 端点
export const getFeatureGates = Generated.adminBillingFeatureGates;

// PIM/JIT Role Activations
export const getRoleActivations = Generated.adminRoleActivations;
export const approveActivation = Generated.adminRoleActivationsApproveByRoleActivationsPost;
export const revokeActivation = Generated.adminRoleActivationsRevokeByRoleActivationsPost;

// Reverse Lookup: "谁有此角色" / "谁有此权限"
export const getRoleUsers = Generated.adminRolesUsersByRoles;
export const getPermissionUsers = Generated.adminPermissionsUsersByPermissions;
export const getPermissionRoles = Generated.adminPermissionsRolesByPermissions;
